name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/python/python-docx.git
          
      - name: Fetch upstream changes
        run: |
          git fetch upstream
          
      - name: Sync master branch
        run: |
          git checkout master
          git merge upstream/master
          git push origin master
        
      - name: Sync main branch (if exists)
        continue-on-error: true
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
